default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: <%= ENV['POSTGRES_DB'] %>
  host: <%= ENV.fetch('DATABASE_HOST', '127.0.0.1') %>
  pool: <%= ENV.fetch('DATABASE_POOL', 10) %>

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB', 'flexioffices_development') %>

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB', 'flexioffices_test') %>

staging:
  <<: *default

com:
  <<: *default

production:
  <<: *default
